sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rafaeltorquato/lab-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rafaeltorquato/lab-docker-react npm run test -- --coverage