version: '3.9'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 3000:3000
    volumes: 
      - /app/node_modules
      - .:/app
    restart: always
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "test"]
    volumes: 
      - /app/node_modules
      - .:/app